### ISSUE TITLE
JFrog CLI not reading environment variables correctly

### ISSUE THREAD

**Issue by kingledion** [jfrog/setup-jfrog-cli#120]
### Describe the bug

A previously working reference to `setup-jfrog-cli@v3` stopped working. The root cause is that the `JF_URL` environment variable does not appear to be recognized. The changed code is here: https://github.com/jfrog/setup-jfrog-cli/pull/117/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R86

It looks like there are unit tests for this specific use case, I cannot tell from looking at the code exactly what is going wrong. 

### Current behavior

The following error:
```
Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are   Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)
```

### Reproduction steps

We are using the action in the following GitHub Action job step:

```
- name: Setup JFrog CLI
        if: steps.validate.outcome == 'success'
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: https://artifactory.tools.bestbuy.com/
          JF_USER: ${{ env.ARTIFACTORY_USERNAME }}
          JF_ACCESS_TOKEN: ${{ env.ARTIFACTORY_ACCESS_TOKEN }}
        with:
          download-repository: generic-jfrog-cli-remote
          version: latest
``

### Expected behavior

Action to complete successfully.This action stopped working with the push of 3.5.0 a few hours ago and we solved issue by pinning version to 3.4.2. 

### Setup JFrog CLI version

3.5.0

### JFrog CLI version

default (2.52.7)

### Workflow operating system type and version

Ubuntu 22.04

### JFrog Artifactory version (if relevant)

Artifactory EnterpriseX 7.71.11

### JFrog Xray version (if relevant)

_No response_

**Comment by sverdlov93** [comment]
Hi @kingledion,
Thanks for reporting this issue.
Our apologies for the inconvenience caused by this bug.
Can you please try again with JFROG_CLI_LOG_LEVEL=DEBUG environment variable and share the full logs?

**Comment by yahavi** [comment]
@kingledion
The release of Setup JFrog CLI version 3.5.1 is now available, featuring a range of bug fixes addressing authentication issues (details can be found at https://github.com/jfrog/setup-jfrog-cli/pull/122).

Kindly inform us if this resolves your issues in the most recent version. Feel free to keep applying the v3 tag to access the latest updates.

**Comment by fschoenm** [comment]
We have  the same issue since today. The latest v3 action didn't fix this.
```
Download action repository 'jfrog/setup-jfrog-cli@v3' (SHA:69c1043e0eb0c4fc94a9d0ad0e87361798ac6084)
...
Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)
```

**Comment by sverdlov93** [comment]
Hi @fschoenm 
Can you please try again on debug mode and share full logs and also your workflow file?
![image](https://github.com/jfrog/setup-jfrog-cli/assets/29822394/708bed8f-aac5-4b2c-853e-f1c26fd0fcd5)

**Comment by fschoenm** [comment]
I don't know if it matters but the setup-jfrog-cli job works, it's the post job that fails.

**Comment by kingledion** [comment]
@yahavi The new version is not fixing the error for us. The same "Post Setup JFrog CLI" step is failing as with @fschoenm's case. 

Debug logs:

```
##[debug]Evaluating: env.ARTIFACTORY_USERNAME
##[debug]Evaluating Index:
##[debug]..Evaluating env:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ARTIFACTORY_USERNAME'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating: env.ARTIFACTORY_ACCESS_TOKEN
##[debug]Evaluating Index:
##[debug]..Evaluating env:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'ARTIFACTORY_ACCESS_TOKEN'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'Post Setup JFrog CLI'
##[debug]Evaluating: always()
##[debug]Evaluating always:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Post Setup JFrog CLI
##[debug]Loading inputs
##[debug]Loading env
Post job cleanup.
::group::Cleanup JFrog CLI servers configuration
Cleanup JFrog CLI servers configuration
 Error: 'download-repository' input provided, but no JFrog environment details found. Hint - Ensure that the JFrog connection details environment variables are set: either a Config Token with a JF_ENV_ prefix or separate env config (JF_URL, JF_USER, JF_PASSWORD, JF_ACCESS_TOKEN)
 ::endgroup::
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Post Setup JFrog CLI
```

**Comment by sverdlov93** [comment]
Hi @kingledion and @fschoenm ,
now that we know that the issue is on the Post install section we found the issue. We will release a fix soon!

**Comment by yahavi** [comment]
@kingledion @fschoenm,
Setup JFrog CLI v3.5.2 has been released, addressing the mentioned issue. Feel free to give it a go, and your feedback would be greatly appreciated.

**Comment by kingledion** [comment]
Yes, confirmed working. Thanks for the fix.

**Comment by fschoenm** [comment]
Also works for us, thanks.
