### ISSUE TITLE
Upgrade to Node.js 20 LTS

### ISSUE THREAD

**Issue by ralf-ovelgoenne** [jfrog/setup-jfrog-cli#129]
### Is your feature request related to a problem? Please describe.

I'm getting this warning:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: jfrog/setup-jfrog-cli@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Describe the solution you'd like to see

Upgrade to Node.js 20. Create new major version release to keep v3 compatible with Node.js 16.

### Describe alternatives you've considered

None

### Additional context

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by yahavi** [comment]
@ralf-ovelgoenne 
Setup JFrog CLI 4.0.0 has been released.
We'd love to hear your thoughts on it.

**Comment by sverdlov93** [comment]
⬆️ ⬆️ ⬆️ 
@JackCoplandGranta, @mmackinnon-bt, @rsi-mrobinson, @nadav13, @swails, @ng-MaximeTroiano, @kduret, @scottleggtrimble, @Jiri-Stary, @JPowell-AA
