### ISSUE TITLE
sudden OIDC failures: Failed to get public key 

### ISSUE THREAD

**Issue by StephenWithPH** [jfrog/setup-jfrog-cli#155]
### Describe the bug

Some time after `Mon, 27 May 2024 15:19:05 GMT` and before `Tue, 28 May 2024 15:50:45 GMT`, `jfrog/setup-jfrog-cli@v4` began failing during the OIDC flow.

The error message is:

```
  Error: Exchanging JSON web token with an access token failed: [{"code":"BAD_REQUEST","message":"Failed to get public key"}]
```

~Note that nothing else changed in the GitHub Action environment or configuration.~

The only change that I can see in the GitHub Action environment between the successful and failed build is the runner image went from

`  Version: 20240516.1.0` to ` Version: 20240526.1.0` (`..0516` -> `..0526`)

### Current behavior

see above

### Setup JFrog CLI version

Download action repository 'jfrog/setup-jfrog-cli@v4' (SHA:727b480bafd0d8adbdfdb2257a7d7c2e08eb1779)

### JFrog CLI version

n/a (happens before Action downloads CLI)

### Workflow operating system type and version

Current runner version: '2.316.1' Ubuntu 22.04.4 LTS (  Version: 20240526.1.0)

### JFrog Artifactory version (if relevant)

SaaS

### JFrog Xray version (if relevant)

SaaS

**Comment by StephenWithPH** [comment]
Following a breadcrumb from https://github.com/jfrog/terraform-provider-platform/issues/71 , we **removed** the trailing slash `https://token.actions.githubusercontent.com/` -> `https://token.actions.githubusercontent.com`, and things resumed working.

**Comment by yahavi** [comment]
Thanks for this @StephenWithPH! I think it will be helpful for others. 
Could you please clarify where you set this value? Is it in the "Provider URL" on the JFrog platform, or is it located in the GitHub settings?
