### ISSUE TITLE
Set User-Agent header to setup-jfrog-cli-github-action/VERSION

### ISSUE THREAD

**Issue by eyalbe4** [jfrog/setup-jfrog-cli#16]
Currently, the User-Agent header sent is by this action is JFrog CLI's default User-Agent value.
I suggest using *setup-jfrog-cli-github-action/VERSION* so that requests going out from this action can be identified.

**Comment by Jatin345Anand** [comment]
Hi,
Can I contribute to this project?
Thanks

**Comment by eyalbe4** [comment]
Sure @Jatin345Anand. Please do.
