### ISSUE TITLE
Bug in Job summary display using v4.1.2

### ISSUE THREAD

**Issue by EricDales** [jfrog/setup-jfrog-cli#168]
### Describe the bug

When using setup-jfrog-cli the job summary has a syntax error that prevents proper display. 

Important note: we are running setup-jfrog-cli on GitHub Enterprise Server 3.11 which might not have the same rendering capabilities as github.com. 

### Current behavior

Here is the display. 

![image](https://github.com/jfrog/setup-jfrog-cli/assets/5948071/e59035a3-2b91-4dd8-87ea-1e847aba7f7d)

### Reproduction steps

Basic usage

### Expected behavior

A correct display 😄 

### Setup JFrog CLI version

4.1.2

### JFrog CLI version

2.57.0

### Workflow operating system type and version

RHEL 8

**Comment by EyalDelarea** [comment]
Hey @EricDales,

Thank you for the bug report! 
We will look into it and attempt to remove the color scheme on unsupported versions of Github enterprise.

I will update you here on the progress.

**Comment by EricDales** [comment]
Thank you for the quick fix !
