### ISSUE TITLE
JFrog Job Summary is not displayed

### ISSUE THREAD

**Issue by gadamsettie2** [jfrog/setup-jfrog-cli#182]
### Describe the bug

When I was using initially the v4 version with sha code 8bab65dc312163b065ac5b03de6f6a5bdd1bec41, it used to display the Jfrog Job Summary and now it no longer displays.

### Current behavior

With the latest sha codes (26532cdb5b1ea07940f10d57666fd988048fc903, 105617d23456a69a92485207c4f28ae12297581d)  probably with the minor patches, the job summary no longer displays. I thought this is a nice cool UI intuitive information. 

### Setup JFrog CLI version

v4

### JFrog CLI version

v4

### Workflow operating system type and version

Windows

**Comment by jpdavis-prof** [comment]
I'm curious about this as well. It sure was handy.

**Comment by EyalDelarea** [comment]
Hi @gadamsettie2,

Thank you for reporting this issue!

Could you please share more details about the runner you're using? what specific image? 

Additionally, could you try manually setting the `disable-job-summary` flag to `false` in the setup-cli action like this:

```
- uses: jfrog/setup-jfrog-cli@v4
  with:
    disable-job-summary: false
```

This information will help us resolve the issue more quickly.

**Comment by gadamsettie2** [comment]
@EyalDelarea ,

I am running these on a self-hosted windows azure VMs (Windows Server 2022 Datacenter version 21H2 & Windows Server 2019 Datacenter).

I have added disable-job-summary flag as true and false. The job summary is not displayed.

Thanks!

**Comment by EyalDelarea** [comment]
Hey @gadamsettie2, @jpdavis-prof 

We've just released a new version `v4.3.1` which should fix this issue.
Please let us know if it resolved the issue for you.

**Comment by maikelvdh** [comment]
@EyalDelarea not sure if it is related, but I am seeing now the following error in the post step:
```
  Error: 9 [Error] failed to get server URL or major version: error extracting server details: platform URL is mandatory for access token creation. This means markdown URLs will be invalid
  Warning: failed while attempting to generate job summary: Error: The process '/opt/hostedtoolcache/jf/2.66.0/x64/jf' failed with exit code 1
```

Should this be made more robust?

**Comment by EyalDelarea** [comment]
> @EyalDelarea not sure if it is related, but I am seeing now the following error in the post step:
> 
> ```
>   Error: 9 [Error] failed to get server URL or major version: error extracting server details: platform URL is mandatory for access token creation. This means markdown URLs will be invalid
>   Warning: failed while attempting to generate job summary: Error: The process '/opt/hostedtoolcache/jf/2.66.0/x64/jf' failed with exit code 1
> ```
> 
> Should this be made more robust?

Hey @maikelvdh ,
It is not related, but you are welcome to open a new issue with this
and please share your setup action code and will try to solve it quickly.

**Comment by gadamsettie2** [comment]
@EyalDelarea ,

Thanks for fixing the issue. It is now displaying the job summary however,  I do see the following error in the post setup Jfrogcli step.

<img width="620" alt="image" src="https://github.com/user-attachments/assets/3f784dc5-810f-44a1-b666-018ca946d17c">

This error wasn't there earlier versions.

Thanks,
Sagar

**Comment by EyalDelarea** [comment]
> @EyalDelarea ,
> 
> Thanks for fixing the issue. It is now displaying the job summary however, I do see the following error in the post setup Jfrogcli step.
> 
> <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/131782842/364014278-3f784dc5-810f-44a1-b666-018ca946d17c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQyMDIsIm5iZiI6MTcyNTM3MzkwMiwicGF0aCI6Ii8xMzE3ODI4NDIvMzY0MDE0Mjc4LTNmNzg0ZGM1LTgxMGYtNDRhMS1iNjY2LTAxOGNhOTQ2ZDE3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxNDMxNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjI5OWY5ZTJlZDc0YmRkYzM2MTRjYjYxMzU2ZWRlNWQxZTI3YzE3MjNkNGQxYmE5YTVlNDc3Mjc1NWRlODc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2RR9jNtKBMK4tCoVZ_4bMq2D1oS7JAn1QpvWY8ovSUo">
> This error wasn't there earlier versions.
> 
> Thanks, Sagar

Here's a rephrased version of your message:

---

Hi @gadamsettie2,

I'm glad to hear the issue has been resolved!

Regarding the post-action failure, it looks like the auto-publish feature is attempting to publish your build, but you don't have the necessary permissions. We'll address this in the next patch.

In the meantime, you can disable this feature by adding the following to your workflow:

```yaml
- uses: jfrog/setup-jfrog-cli@v4
  with:
    disable-auto-build-publish: true
```

**Comment by EyalDelarea** [comment]
Hi @gadamsettie2,

I'm closing this issue to help us better track ongoing issues. If you encounter any further problems, please don't hesitate to open a new issue.

@maikelvdh, the same goes for you—if the error persists, kindly open a new issue and include as many details as possible so we can address it.

Thank you all for your feedback!
