### ISSUE TITLE
Cleanup error: Unable to find jf executable

### ISSUE THREAD

**Issue by zoranjurcevic** [jfrog/setup-jfrog-cli#200]
### Describe the bug

Hello team,

I'm currently experiencing an issue with the cleanup stage on my GitHub Actions pipelines. I've noticed it only a couple of hours ago and I'm thinking it is related to [the previous cleanup issue from yesterday](https://github.com/jfrog/setup-jfrog-cli/issues/196) and the recent changes in 4.3.x but of course I'll let you guys confirm if that is the case. Do let me know if you need any additional information!

### Current behavior

The errors are the following:

```
Error: Failed to parse JSON: Error: Unable to locate executable file: jf. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Warning: failed while attempting to generate job summary: Error: Unable to locate executable file: jf. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Error: Unable to locate executable file: jf. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

They're all slightly different but they do lead to the same issue: `jf` not being found in path. 

### Reproduction steps

To reproduce, use the GitHub Action:

```yaml
    - name: 'Set up JFrog CLI'
      uses: jfrog/setup-jfrog-cli@v4
      with:
        version: 2.66.0
        disable-job-summary: false
        disable-auto-build-publish: false
```

### Expected behavior

The cleanup should be done without errors.

### Setup JFrog CLI version

4.3.2

### JFrog CLI version

2.66.0

### Workflow operating system type and version

Github action runner

**Comment by caiocsgomes** [comment]
We are facing the same, this started yesterday but we notice some moments ago. This stucks pipelines using the action as the cleanup at the end is stuck holding the runners instead of releasing it.

**Comment by sverdlov93** [comment]
Hi @caiocsgomes and @zoranjurcevic , Did you try with [latest](https://github.com/jfrog/setup-jfrog-cli/releases/tag/v4.3.2) version?

**Comment by caiocsgomes** [comment]
Is latest set by default? I'm not passing a version

**Comment by caiocsgomes** [comment]
Log for the run:

Run jfrog/setup-jfrog-cli@v4
  with:
    version: 2.66.0
    disable-job-summary: false
    disable-auto-build-publish: false

**Comment by zoranjurcevic** [comment]
Hi @sverdlov93 yes, I've made sure to clean the cache so the runners download latest. The issue persists.

**Comment by caiocsgomes** [comment]
How can we specify the prior version for the action? I just see the option to setup the cli version in the docs

**Comment by sverdlov93** [comment]
Hi @caiocsgomes, @zranjurcevic @rorynickolls-skyral and @ajmalab 
Our apologies for the inconvenience caused by this.
This [PR](https://github.com/jfrog/setup-jfrog-cli/pull/201) should fix it.
I will update this thread once the next release will be out.

**Comment by sverdlov93** [comment]
Hi @caiocsgomes, @zoranjurcevic @rorynickolls-skyral and @ajmalab
We believe that the issue was fixed on https://github.com/jfrog/setup-jfrog-cli/releases/tag/v4.4.1 
Looking forward to your feedback on it. your feedback!
