### ISSUE TITLE
JFrog CLI with Certificates Doesn't Work with GitHub Action

### ISSUE THREAD

**Issue by vesubramanian** [jfrog/setup-jfrog-cli#40]
**JFrog CLI with Certificates Not Working with GitHub Actions**
My Artifactory instance is configured to use a certificate. Hence while configuring JFrog CLI, I have to provide the Client Certificate Path and Client Certificate Key Path. Both these are local paths (say C:\Path-of-certificate). I am running jfrog cli on Windows 10 and the cli is the latest (1.47.1). After this, I exported this token and created an org level secret and used it in my workflow. While trying to do jfrog rt ping, it is trying to locate the certificate from a physical path specified during rt cli configuration. 

**To Reproduce**
Use Client Certificate and Key Path during CLI configuration

**Versions**
- Setup JFrog CLI version: 1.47.1
- Workflow operating system: ubuntu-latest
- JFrog CLI version: 1.47.1
- Artifactory Version: 7.12.8

**Comment by yahavi** [comment]
@vesubramanian,
Thanks for using Setup JFrog CLI GitHub Action.

To use self-signed certificate, you can do the following:
1. Export server containing a path in your agent's workspace
2. Save the certificate and the certificate key as secrets
2. At the beginning of the workflow, write the certificate and the certificate key to the files in the paths determined in 1.

Please let me know if that helped.
