### ISSUE TITLE
Hardcoded `v1` path prevents usage of `v2` cli

### ISSUE THREAD

**Issue by Lykathia** [jfrog/setup-jfrog-cli#50]
**Describe the bug**
Version 2 of the CLI is out, and recommended for usage. It is unable to be used with this action.

**To Reproduce**
https://github.com/jfrog/setup-jfrog-cli/blob/cd5a0e8f80d91ebc0e777b1e8d4bcfda690211ae/src/utils.ts#L42

**Expected behavior**
JFROG_CLI_VERSION should be respected, regardless of version.

**Versions**
- Setup JFrog CLI version: 1.2.0
- Workflow operating system: ubuntu
- JFrog CLI version: any 2.0

**Comment by mmege** [comment]
I've just propose a PR with a quick fix about that.

**Comment by yahavi** [comment]
@mmege & @Lykathia ,
We released Setup JFrog CLI v1.2.1 (synced with v1). This version includes #51 (Thanks @mmege for this contribution!).

We'd appreciate your feedback on that.
