### ISSUE TITLE
Existing JFROG_CLI_BUILD variables are overwritten

### ISSUE THREAD

**Issue by tshowers-bt** [jfrog/setup-jfrog-cli#69]
**Describe the bug**
The action overwrites existing values for `JFROG_CLI_BUILD_NAME` and `JFROG_CLI_BUILD_NUMBER` with the workflow name and run number.

**To Reproduce**
- Set `JFROG_CLI_BUILD_NAME` and `JFROG_CLI_BUILD_NUMBER` in the `env` context for a workflow or job.
- Use the `setup-jfrog-cli` action for a job step.
- Refer to `JFROG_CLI_BUILD_NAME` and `JFROG_CLI_BUILD_NUMBER` in subsequent steps.

**Expected behavior**
Existing values for `JFROG_CLI_BUILD_NAME` and `JFROG_CLI_BUILD_NUMBER` are not overridden.

**Versions**
- Setup JFrog CLI version: 2.1.0
- Workflow operating system: ubuntu-latest

**Additional context**
The docs say these values will be set so this may be intentional, but I would only expect them to be set if there is no existing value. As it is now a job has to set the env to the desired values after the action has run which seems especially cumbersome in a workflow with multiple jobs that use the setup action where you'd expect a single declaration in the workflow `env` to be sufficient.

**Comment by yahavi** [comment]
@tshowers-bt,
Thanks for reporting this issue!
Setup JFrog CLI 2.3.0 is released. This version includes a fix for this issue.
We'd appreciate your feedback on that.
