### ISSUE TITLE
Upgrade to 1.0.3 breaks

### ISSUE THREAD

**Issue by jasonmcintosh** [jfrog/setup-jfrog-cli#8]
[Error] This operation requires Docker version 17.07.0 or higher.
##[error]Process completed with exit code 1.

When I go back to 1.0.2 I'm able to run builds.

**Comment by yahavi** [comment]
@jasonmcintosh 
Version 1.0.3 includes only [dependencies updates](https://github.com/jfrog/setup-jfrog-cli/commit/0ff6419890667e3f7b38c9791862da143edfceae#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33-R38).
The default JFrog CLI version had been updated to 1.33.1. You can still use 1.0.3 with JFrog CLI 1.32.4 by [mention it in your workflow](https://github.com/jfrog/setup-jfrog-cli#setting-jfrog-cli-version):
```yaml
- uses: jfrog/setup-jfrog-cli@v1
  with:
    version: 1.32.4
```
We're sorry for the inconvenience.

**Comment by yahavi** [comment]
@jasonmcintosh,
I checked with my team about the docker version verification. This verification was put in place after we realized that [docker login](https://github.com/jfrog/jfrog-cli/blob/master/artifactory/utils/docker/docker.go#L214) may not work properly when it is invoked by JFrog CLI, with version of docker below 17.07.
Hence, you are strongly recommended to use the default (or latest) JFrog CLI and upgrade the docker version. You can try [Setup-Docker](https://github.com/marketplace/actions/setup-docker) to upgrade docker to the latest version in Linux.
You may also need the latest JFrog CLI for your other [issue](https://github.com/jfrog/jfrog-cli/issues/606).

**Comment by jasonmcintosh** [comment]
Note the default github action is:
```Docker version 3.0.10+azure, build 99c5edceb48d64c1aa5d09b8c9c499d431d98bb9```
I've reverted back to 1.32.4 for now as it seems fine with the azure version.

**Comment by yahavi** [comment]
Thanks for this information, @jasonmcintosh!
We are working on a fix: Instead of checking the docker client version, we will check the docker client **API** version.
You can track this PR: https://github.com/jfrog/jfrog-cli/pull/623.

**Comment by yahavi** [comment]
@jasonmcintosh,
JFrog CLI 1.35.1 is released. This version includes the fix.
Feel free to upgrade.
We'll appreciate your feedback for that!

**Comment by eyalbe4** [comment]
Clarification - JFrog CLI 1.35.1 includes the fix, but it is not the default version of the setup-jfrog-cli GitHub Action. The CLI version needs to be set, as described in the Action's documentation.

**Comment by eyalbe4** [comment]
@jasonmcintosh,
Version 1.0.4 of the *setuo-jfrog-cli* GitHub Action is released and includes the latest JFrog CLI release as the default. Please let us know if it resolves the issue for you.
