### ISSUE TITLE
What is --server-id?

### ISSUE THREAD

**Issue by sergiomarotco** [jfrog/setup-jfrog-cli#86]
Hi,
please give a real example of what the server-id variable looks like.

My xray server is: artifactory.congo123.com/xray
My Artifactory is: artifactory.congo123.com/artifactory

what is --server-id ?

**Comment by eyalbe4** [comment]
@sergiomarotco,
You can choose any value for the Server ID when configuring your JFrog instances using the `jf c add` command. This Server ID value can then be used as `-server-id` in other commands. 
Also use the `jf c show` to see the instances you previously configured.

**Comment by sverdlov93** [comment]
You can configure multiple configurations on your machine and switch between them using the --server-id flag.
Read more here - https://www.jfrog.com/confluence/display/CLI/JFrog+CLI#JFrogCLI-JFrogPlatformConfiguration

```
> jf c show

Server ID:			mictest
JFrog platform URL:		https://michaeltest.jfrog.io/
Artifactory URL:		https://michaeltest.jfrog.io/artifactory/
Distribution URL:		https://michaeltest.jfrog.io/distribution/
Xray URL:			https://michaeltest.jfrog.io/xray/
Mission Control URL:		https://michaeltest.jfrog.io/mc/
Pipelines URL:			https://michaeltest.jfrog.io/pipelines/
User:				michaelsv@jfrog.com
Password:			***
Access token:			***
Default:			true

Server ID:			bs-test
JFrog platform URL:		http://10.70.30.17:8082/
Artifactory URL:		http://10.70.30.17:8082/artifactory/
Distribution URL:		http://10.70.30.17:8082/distribution/
Xray URL:			http://10.70.30.17:8082/xray/
Mission Control URL:		http://10.70.30.17:8082/mc/
Pipelines URL:			http://10.70.30.17:8082/pipelines/
Access token:			***
Default:			false

```

**Comment by niranjanakoni** [comment]
Hey @sverdlov93, is there any option to use `JF_SERVER_ID` as env variables in [jfrog/setup-jfrog-cli@v4.2.2](https://github.com/marketplace/actions/setup-jfrog-cli) action?

**Comment by sverdlov93** [comment]
Hi @niranjanakoni , you can use JFROG_CLI_SERVER_ID

**Comment by niranjanakoni** [comment]
Hi @sverdlov93, can we use JFROG_CLI_SERVER_ID like this?

```bash
- uses: jfrog/setup-jfrog-cli@v4
   env:
     JF_URL: ${{ vars.JF_URL }}
     JF_USER: ${{ secrets.JF_USER }}
     JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
     JFROG_CLI_SERVER_ID: ${{ secrets.JFROG_CLI_SERVER_ID }}
```

**Comment by sverdlov93** [comment]
@niranjanakoni 
No, setup-jfrog-cli creates server configuration with a default server-id using the provided credentials.
If you want to create another server configuration during your workflow you can use the JFROG_CLI_SERVER_ID environment variable to make JFrog CLI command use this server-id instead of the default created by the GitHub action.

**Comment by tomjfrog** [comment]
+1 to this capability.  The significance of Server ID is not only for JF setup commands, but it's needed to reference the correct server ID in any of the Package Manager integration steps.  

A reasonable alternative would be to at least make the default server ID an `output` value of the step that bootstraps the JF CLI and sets the Server ID.
