### ISSUE TITLE
node 12 deprecation

### ISSUE THREAD

**Issue by lukasz-mitka** [jfrog/setup-jfrog-cli#87]
**Is your feature request related to a problem? Please describe.**
I'm getting this warning:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jfrog/setup-jfrog-cli, jfrog/setup-jfrog-cli
```

**Describe the solution you'd like to see**
Upgrade to Node.js 16. Create new major version release to keep v2 compatible with Node.js 12.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by calexander3** [comment]
+1 I just started seeing this too.

**Comment by sulfasTor** [comment]
+1 Our teams are heavily using frog actions and runners are starting to complain.

**Comment by yarinsa** [comment]
+1

**Comment by lukasz-mitka** [comment]
@sverdlov93 FYI

**Comment by sverdlov93** [comment]
Hi @lukasz-mitka , @qubitz , @ynixon, @calexander3, @sulfasTor , @yarinsa 
[Setup JFrog CLI 3.0.0](https://github.com/jfrog/setup-jfrog-cli/releases/tag/v3.0.0) is released with Node16.
Looking forward to your feedback on it.

**Comment by yarinsa** [comment]
> Hi @lukasz-mitka , @qubitz , @ynixon, @calexander3, @sulfasTor , @yarinsa and @AnttiHal [Setup JFrog CLI 3.0.0](https://github.com/jfrog/setup-jfrog-cli/releases/tag/v3.0.0) is released with Node16. Looking forward to your feedback on it.

So far so good, thanks
